### PR TITLE
Add support to protected keys

### PR DESCRIPTION
**Pull request by krolow**
It add support to passphrase/password keys, it will remove in container the password to use the key

### CODE REVIEW

**Comment by maxclaus** [comment]
@krolow approved. Go for it.

**Comment by esnunes** [comment]
I think the use of environment variable is more appropriate as we already use environment variable for other vault configurations.

**Comment by krolow** [comment]
I have discuss internally with @maxcnunes and we would like to avoid the storage of plain text password... so that's why we have add the argument

**Comment by esnunes** [comment]
But you still can do it defining the environment variable in the command line...

**Comment by maxclaus** [comment]
Sure you can. But related to password I think is better restrict the password value to the ONVAULT scope. Otherwise people could set env variables in the Dockerfile and it would be available in the containers "forever".

**Comment by NikolausDemmel** [comment]
So you out the password in plaintext in the dockerfile? Won't that also bake it into the image?

**Comment by esnunes** [comment]
print.sh
```
#!/bin/sh
echo $MY_VAR
```
Dockerfile
```
FROM alpine:3.4
ADD print.sh /print.sh
RUN chmod +x /print.sh
RUN MY_VAR=hello /print.sh
```

The snippet above will print `hello`. In any case I wouldn't recommend create a Dockerfile with a password written on it. The only way to use it safe is:
- run onvault using an existing image `docker run --rm image:latest ONVAULT npm install`;
- using a preprocessor which will replace a key in the Dockerfile by the real password before build the image, e.g. `RUN ONVAULT --disable-pwd %MY_PASS%`;

Both will have the same behavior, I'm only in favor of environment variable in order to keep the standard vault configuration and looks like it is confusing.

**Comment by NikolausDemmel** [comment]
I'm confused. Unless I am mistaken, in all cases you mentioned the password will  end up in the final docker image...

**Comment by krolow** [comment]
i don't see a way to avoid to have the password in that case...

my first attempt was using the env variable, but after talk with @maxcnunes he mention that would be better to use param, that I don't see any problem in use as well... if someone want I can change later to env variable back

but I'm already using it here and it's working :) in my case it's not to build images it's to run arbitrary `npm install` a long o the development

**Comment by esnunes** [comment]
@NikolausDemmel AFAIK the images don't contain the Dockerfile used to build them unless you ADD the Dockerfile itself to the image. In case you want to avoid that you can simply create .dockerignore like this:

.dockerignore
```
Dockerfile
```

**Comment by NikolausDemmel** [comment]
Every line in a Dockerfile is part of the meta data of the resulting image. See also the history command:

https://docs.docker.com/engine/reference/commandline/history/

**Comment by esnunes** [comment]
I wasn't aware of the history command. Having this in mind I think there is no safe way of using the `ONVAULT` command with password.

A better alternative might be to provide the password during the launch of the vault server.

**Comment by NikolausDemmel** [comment]
Yeah it kind of would make sense to pass a password to the vault server and let it serve the keys unprotected.

There is also some upstream work on this, but not sure how long till this becomes available: https://github.com/docker/docker/issues/13490#issuecomment-263573917

**Comment by krolow** [comment]
@esnunes I think it would be better to use in server, but currently server is dumb, it just tar everything from ssh and provides it to client, client is the one that is already dealing in choose what pem key to use https://github.com/dockito/vault/blob/master/ONVAULT#L64

So it would involve change a bit server to start accept the 'pem' to use and the pass, it is what the other similar project does: https://github.com/ericvicenti/ssh-keygen

I think we can create one issue to make these changes.

**Pull request merged**
