### PR TITLE
Support for optional ~/.ssh/vault directory, switch to nginx, output fingerprint from ONVAULT

### PR DESCRIPTION
**Pull request by wormzer**
optional ~/.ssh/vault directory
nginx served up static tgz
shows key fingerprint during usage in ONVAULT

### CODE REVIEW

**Comment by wormzer** [comment]
I really like your approach here, bravo! I found your project from this thread https://github.com/docker/docker/issues/6396.

I originally started a completely fresh project, but there were actually so many similarities to your vault I brought it in line with your work. My biggest issue was needing a key other than ~/.ssh/id_rsa for my private git repo, but didn't want people to have to create their own docker-compose.yml. I hope you can use something from here for your project.

Thanks for the inspiration. This really works well for me.

**Comment by pirelenito** [comment]
Hi @wormzer thanks for getting interested in the project and taking the time to submit this pull request. I am really happy your enjoyed the solution :smiley: and thankful for your contribution.

Regarding your pull request, although I enjoyed the simplicity of having a simple Nginx running, it poses a drawback... a change in the key files would required a restart in the vault container. Since we currently use it as a service in our build infrastructure and in our local [development boxes](https://github.com/dockito/devbox) I still prefer the solution of having the `tgz` being generated dynamically, hence the simple Node.js approach.

About the optional `.ssh/vault` directory, couldn't it be solved by simply mapping a different volume while spinning up the container? Something like:

``` bash
docker run -p 172.17.42.1:14242:3000 -v ~/.ssh/vault:/vault/.ssh dockito/vault
```

Our goal was to have your entire `.ssh` folder available inside the container, so any custom configuration in the `config` file and different keys would also be available there. So you could have something like this at your `~/.ssh/config` to use different keys for different hosts:

```
Host your-server.testing.com
  HostName your-server.testing.com
  Port 30522
  IdentityFile ~/.ssh/custom_identity_file
```

Let me know your thoughts.

**Comment by wormzer** [comment]
All good feedback, and I figured out some of those issues shortly after submitting the patch. This was my first venture into interesting docker territory and was fun to disassemble / reassemble. 

Good luck with your project going forward and I will continue to look for ways to enhance it.

**Comment by pirelenito** [comment]
Thanks again!

**Pull request closed without merging**
